### ISSUE TITLE
Feature request: cancel

### ISSUE THREAD

**Issue by chetan51** [mbostock/queue#21]
It would be great to be able to do:

	var q = queue(1);
	tasks.forEach(function(t) { q.defer(t); });
	q.awaitAll(function(error, results) { console.log("all done!"); });

	// At a later time, before "all done!" is printed
	q.cancel();

And all the remaining tasks become no-ops.

**Comment by brhlavinka** [comment]
Thanks for writing the abort branch!

**Comment by mbostock** [comment]
This issue is covered by #22, so closing as duplicate.

**Comment by mbostock** [comment]
Released in 1.2.
