### ISSUE TITLE
q.length(), q.running()

### ISSUE THREAD

**Issue by mvayngrib** [mbostock/queue#29]
first of all, nice small lib :)

It would be nice to be able to do q.length() to see how many tasks are queued, and q.running() / q.active() to see how many tasks are currently running.

**Comment by el3ment** [comment]
+1 -- "remaining" is a private variable, it would be great to expose it via something like this

**Comment by thbar** [comment]
Seconded, it would be great to be able to do that! It's apparently available in a fork ad01c73b9e2a93a67ffb019290012625a119a977

**Comment by mbostock** [comment]
Folding this request into #46.
