### ISSUE TITLE
Re-submit job to queue again

### ISSUE THREAD

**Issue by reidlai** [mbostock/queue#31]
Dear All,

I have an object which has a refresh method to create queue object and use defer method to submit jobs.  I also implement awaitAll to emit an event.  Everything works fine in my app first run. But when I try to rerun my refresh method, I found that all jobs did submit through defer (proved by logging each callback). But I cannot see awaitAll being called.  How can I reset the queue to make awaitAll works when I re-submit jobs?  Thanks for your advice.

**Comment by mbostock** [comment]
There is no way to reset the queue (under the current API). You must discard your existing queue and create a new one.
