### ISSUE TITLE
Reusing queues

### ISSUE THREAD

**Issue by rsmith31415** [mbostock/queue#38]
Sorry I post this here, but I didn't find a google group for this kind of issue. 

I posted a [question](http://stackoverflow.com/questions/32152962/reusing-queue-after-awaitall-in-queue-js) on SO a couple of days ago but it hasn't received much attention. The main idea is that I want to reuse a queue, but I realized that after using the queue more than one time, the q.awaitAll function is receiving previous results. This is the code:

```
<!DOCTYPE html>
<html>
    <head>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/queue-async/1.0.7/queue.min.js"></script>
    </head>
    <body>
        <button id="send">Send</button>
    </body>
    <script>
        var button = document.querySelector('#send');
        var q = queue(1);
        var i = 0;
        button.addEventListener('click', function() {
            var message = i++;
            q.defer(function(message, callback) {
                setTimeout(function() {
                    callback(null, message);
                }, 3000);
            }, message);
        });

        q.awaitAll(function(err, result) {
            console.log(result);
        });
    </script>
</html>
```

After clicking the button once, I receive [0], but clicking the button again doesn't remove previous results (instead, I get [0,1]) and the array grows after each click.

Is this the intended behavior? Is there some way to reuse the queue?

Thanks

**Comment by mbostock** [comment]
You’re not supposed to reuse queues. Throw them away when you’re done and create a new one.

(Sorry it took me so long to respond…)
